name = "wisesum-api"
main = "src/index.ts"
compatibility_date = "2025-12-23"

[env.staging]
name = "wisesum-api-staging"
routes = [
  { pattern = "api-staging.wisesum.app/*", zone_name = "wisesum.app" }
]

[env.production]
name = "wisesum-api"
routes = [
  { pattern = "api.wisesum.app/*", zone_name = "wisesum.app" }
]
